apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-backend
  labels:
    app: counter-backend
    app.kubernetes.io/part-of: counter-app
  namespace: 254501-samready
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-backend
  template:
    metadata:
      name: counter-backend
      labels:
        app: counter-backend
    spec:
      containers:
        - name: counter-backend
          image: ghcr.io/heldertheking/counter-backend:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: npm_config_cache
              value: ./.npm-cache
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: counter-database
                  key: database-host
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: counter-database
                  key: database-name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: counter-database
                  key: database-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: counter-database
                  key: database-password
            - name: NODE_ENV
              value: production
            - name: PASSPHRASE
              value: secret
      restartPolicy: Always